ClinicPresentationLayer/Pages/Staffs/Index.cshtml.cs
using BusinessObjects;
using BusinessObjects.Entities;
using ClinicPresentationLayer.Authorization;
using ClinicServices.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;

namespace ClinicPresentationLayer.Pages.Staffs
{
    [CustomAuthorize(UserRoles.ClinicOwner)]
    public class IndexModel : PageModel
    {
        private readonly IUserService _userService;


        public IndexModel(IUserService userService)
        {
            _userService = userService;

        }
        [BindProperty]
        [Required]
        public string Username { get; set; }

        [BindProperty]
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [BindProperty]
        public User User { get; set; } = default!;
        public IList<User> Staffs { get; set; } = default!;

        public async Task OnGetAsync()
        {
            Staffs = await _userService.GetAllStaffAsync();
        }
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            try
            {
                Staffs = await _userService.GetAllStaffAsync();
                bool isUsernameExisted = await _userService.IsUsernameExisted(Username);
                if (isUsernameExisted)
                {
                    TempData["ErrorMessage"] = "Username already existed";
                    return Page();
                }

                Staffs = await _userService.GetAllAsync();
                User newUser = new() { Username = Username, Role = UserRoles.Staff, Password = Password };

                var result = await _userService.AddAsync(newUser);
                if (result != null)
                {
                    return RedirectToPage("./Index");
                }
                else
                {
                    return Page();
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return Page();
            }

        }
    }
}

ClinicPresentationLayer/Pages/Staffs/Main.cshtml.cs
using BusinessObjects;
using BusinessObjects.Entities;
using ClinicPresentationLayer.Authorization;
using ClinicPresentationLayer.Extension;
using ClinicServices;
using ClinicServices.Interfaces;
using MailKit.Search;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Transactions;

namespace ClinicPresentationLayer.Pages.Staffs
{
    [CustomAuthorize(UserRoles.Staff)]
    public class MainModel : PageModel
    {
        private readonly IPatientService _patientService;
        private readonly IAppointmentService _appointmentService;
        private readonly IServiceService _serviceService;
        private readonly IDentistAvailabilityService _dentistAvailService;
        private readonly IPaymentService _paymentService;
        public MainModel(IPatientService patientService, IAppointmentService appointmentService, IServiceService serviceService, IDentistAvailabilityService dentistAvailabilityService, IPaymentService paymentService)
        {
            _patientService = patientService;
            _appointmentService = appointmentService;
            _dentistAvailService = dentistAvailabilityService;
            _serviceService = serviceService;
            _paymentService = paymentService;
        }
        public List<BusinessObjects.Entities.Appointment> PatientAppointments { get; set; }
        [BindProperty(SupportsGet = true)]
        public string SearchTerm { get; set; }
        public Patient FoundPatient { get; set; }
        public decimal? RefundAmount { get; set; }
        public string ErrorMessage { get; set; }
        public string CheckMessage { get; set; }
        [BindProperty]
        public BusinessObjects.Entities.Appointment Appointment { get; set; } = default!;
        [BindProperty]
        public Service Service { get; set; } = default!;
        [BindProperty]
        public List<Service> Services { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync()
        {
            Services = await _serviceService.GetAllAvailAsync();
            Service = Services.First();
            if (!string.IsNullOrEmpty(SearchTerm))
            {
                FoundPatient = await _patientService.FindPatientAsync(SearchTerm);
                if (FoundPatient != null)
                {
                    PatientAppointments = await _appointmentService.GetAppoinmentHistoryAsync(FoundPatient.Id);
                    TempData["PatientId"] = FoundPatient.Id;
                }
            }
            
            ErrorMessage = TempData["ErrorMessage"] as string;
            CheckMessage = TempData["SuccessMessage"] as string;
            return Page();
        }
        public async Task<IActionResult> OnPostSearchAsync()
        {
            Services = await _serviceService.GetAllAvailAsync();
            Service = Services.First();
            if (string.IsNullOrEmpty(SearchTerm))
            {
                TempData["ErrorMessage"] = "Search term is required.";
                return Page();
            }

            FoundPatient = await _patientService.FindPatientAsync(SearchTerm);
            if(FoundPatient != null)
            {
                PatientAppointments = await _appointmentService.GetAppoinmentHistoryAsync(FoundPatient.Id);
            }
            TempData["PatientId"] = FoundPatient.Id;
            if (FoundPatient == null)
            {
                TempData["ErrorMessage"] = "No patient found with the provided details.";
            }

            return Page();
        }
        public async Task<IActionResult> OnPostCheckRefundAsync(int appointmentId)
        {
            ErrorMessage = TempData["ErrorMessage"] as string;
            CheckMessage = TempData["SuccessMessage"] as string;
            var appointment = await _appointmentService.GetAppointmentsByIdAsync(appointmentId);
            if (appointment == null)
            {
                TempData["ErrorMessage"] = "No appointment found with the provided ID.";
                return RedirectToPage(new { SearchTerm });
            }
            if(appointment.Payment == null)
            {
                TempData["ErrorMessage"] = "No payment found with the appointment.";
                return RedirectToPage(new { SearchTerm });
            }

            if (appointment.Payment.PaymentStatus != PaymentStatus.CHECKOUT)
            {
                TempData["ErrorMessage"] = "The appointment is not eligible for a refund. The Staff only allow to refund offline appointment";
                return RedirectToPage(new { SearchTerm });
            }

            var cancellationTimeSpan = DateTime.UtcNow.AddHours(7) - appointment.CreateDate;
            RefundAmount = cancellationTimeSpan.TotalDays < 1
                ? appointment.Payment.Amount // Full refund
                : appointment.Payment.Amount * 0.5M; // 50% refund
            TempData["SuccessMessage"] = $"Refund valid for {RefundAmount}";
            return RedirectToPage(new { SearchTerm });
        }

        public async Task<IActionResult> OnPostRefundAsync(int appointmentId)
        {
            var appointment = await _appointmentService.GetAppointmentsByIdAsync(appointmentId);
            if (appointment == null)
            {
                TempData["ErrorMessage"] = "No appointment found with the provided ID.";
                return RedirectToPage(new { SearchTerm });
            }

            if (appointment.Payment.PaymentStatus != PaymentStatus.CHECKOUT)
            {
                TempData["ErrorMessage"] = "The appointment is not eligible for a refund. The Staff only allow to refund offline appointment";
                return RedirectToPage(new { SearchTerm });
            }

            var cancellationTimeSpan = DateTime.UtcNow.Date - appointment.CreateDate.Date;
            var refundAmount = cancellationTimeSpan.TotalDays < 1
                ? appointment.Payment.Amount // Full refund
                : appointment.Payment.Amount * 0.5M; // 50% refund

            using (var scope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
            {
                try
                {
                    if(cancellationTimeSpan.TotalDays < 1)
                    {
                        await _appointmentService.UpdateAppointmentStatus(appointmentId, (int)AppointmentStatus.Canceled, null);
                    }
                    else
                    {
                        await _appointmentService.UpdateAppointmentStatus(appointmentId, (int)AppointmentStatus.LateCanceled, null);
                    }
                    
                    TempData["SuccessMessage"] = $"Refund of {refundAmount} processed successfully.";
                    scope.Complete();
                }
                catch (Exception ex)
                {
                    TempData["ErrorMessage"] = $"Failed to process refund: {ex.Message}";
                }
            }

            //PatientAppointments = await _appointmentService.GetAppoinmentHistoryAsync(FoundPatient.Id);
            return RedirectToPage(new { SearchTerm });
        }
        public async Task<IActionResult> OnPostCheckInAsync(int appointmentId)
        {
            var appointment = await _appointmentService.GetAppointmentsByIdAsync(appointmentId);
            if (appointment == null)
            {
                TempData["ErrorMessage"] = "No appointment found with the provided ID.";
                return RedirectToPage(new { SearchTerm });
            }

            if (appointment.Status != (int)AppointmentStatus.Waiting)
            {
                TempData["ErrorMessage"] = "The appointment is not eligible for check-in.";
                return RedirectToPage(new { SearchTerm });
            }

            try
            {
                await _appointmentService.UpdateAppointmentStatus(appointmentId, (int)AppointmentStatus.Checkin, null);
                TempData["SuccessMessage"] = "Checked in Patient successfully.";
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"Failed to check in patient: {ex.Message}";
            }

            return RedirectToPage(new { SearchTerm });
        }

        public async Task<IActionResult> OnPostSubmitAsync()
        {
            var currentAcc = HttpContext.Session.GetObject<User>("UserAccount");
            Services = await _serviceService.GetAllAsync();
            if (currentAcc == null)
            {
                return RedirectToPage("/Login");
            }
            try
            {
                Appointment.PatientId = TempData["PatientId"] as int? ?? throw new Exception("Patient id not found");

                Service = await _serviceService.GetByIdAsync(Appointment.ServiceId);
                if (Service == null)
                {
                    TempData["ErrorMessage"] = "Service not found";
                    return Page();
                }

                var availRoom = _appointmentService.GetRoomAvailable(Appointment.AppointDate, Service.Duration, Appointment.StartSlot);
                Appointment.RoomId = availRoom.Id;
                Appointment.Status = (int)AppointmentStatus.Waiting;
                Appointment.CreateDate = Appointment.ModifyDate = DateTime.UtcNow.AddHours(7);
                Appointment.EndSlot = Appointment.StartSlot + Service.Duration - 1;
                var payment = new Payment
                {
                    Amount = Service.Cost.Value,
                    PaymentStatus = PaymentStatus.CHECKOUT,
                    PaymentDate = DateTime.UtcNow.AddHours(7),
                    TransactionId = Guid.NewGuid().ToString()
                };
                await _appointmentService.AddAsync(Appointment, payment);
                return RedirectToPage(new { SearchTerm });
            }
            catch(Exception ex) 
            {
                TempData["ErrorMessage"] = $"error when create appointment: {ex.Message}";

ClinicPresentationLayer/Pages/Staffs/RegisterPatient.cshtml.cs
using BusinessObjects.Entities;
using BusinessObjects;
using ClinicPresentationLayer.Authorization;
using ClinicServices.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ClinicPresentationLayer.Pages.Staffs
{
    [CustomAuthorize(UserRoles.Staff)]
    public class RegisterPatientModel : PageModel
    {
        private readonly IPatientService _patientService;

        public RegisterPatientModel(IPatientService patientService)
        {
            _patientService = patientService;
        }

        [BindProperty]
        public string Username { get; set; }

        [BindProperty]
        public string Password { get; set; }

        [BindProperty]
        public string Name { get; set; }

        [BindProperty]
        public string Email { get; set; }

        [BindProperty]
        public DateOnly DateOfBirth { get; set; }

        [BindProperty]
        public string Gender { get; set; }

        [BindProperty]
        public string Phone { get; set; }

        [BindProperty]
        public string Address { get; set; }

        public async Task<IActionResult> OnPostRegister()
        {
            try
            {
                User newUser = new() { Username = Username, Role = UserRoles.Patient, Password = Password };
                Patient newPatient = new()
                {
                    Email = Email,
                    Name = Name,
                    Address = Address,
                    DateOfBirth = DateOfBirth,
                    Gender = Gender,
                    Phone = Phone
                };
                var check = await _patientService.StaffAddAsync(newPatient, newUser);
                if (check != null)
                {
                    TempData["SuccessMessage"] = "Patient account created successfully.";
                    return RedirectToPage("/Staffs/Main");
                }
                else
                {
                    TempData["ErrorMessage"] = "An error occurred while creating the patient account.";
                    return Page();
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return Page();
            }
        }
    }
}

ClinicPresentationLayer/Pages/Staffs/Main.cshtml
 @page
@using BusinessObjects;
@using BusinessObjects.Entities;
@model ClinicPresentationLayer.Pages.Staffs.MainModel
@{
}
<body class="auth">
    <div id="main-wrapper" class="show">
        <div class="login-tabib">
            <div>
                <div class="text-center">
                    <a class="logo" href="index.html">
                        <img class="img-fluid" src="~/images/logo.png" alt="login page">
                    </a>
                </div>
                <h4>Search for a patient</h4>
                <form method="get">
                    <div class="form-group">
                        <label for="SearchTerm">Search Term</label>
                        <input id="SearchTerm" name="SearchTerm" class="form-control" value="@Model.SearchTerm" />
                        <span asp-validation-for="SearchTerm" class="text-danger"></span>
                    </div>
                    <button type="submit" class="btn btn-primary">Search</button>
                </form>
                @if (Model.ErrorMessage != null)
                {
                    <div class="alert alert-danger">
                        @Model.ErrorMessage
                    </div>
                }
                @if (Model.CheckMessage != null)
                {
                    <div class="alert alert-success">
                        @Model.CheckMessage
                    </div>
                }
                @if(Model.FoundPatient != null)
                {
                    <div>
                        <h4>Patient Details</h4>
                        <p>Name: @Model.FoundPatient.Name</p>
                        <p>Email: @Model.FoundPatient.Email</p>
                        <p>Date of Birth: @Model.FoundPatient.DateOfBirth</p>
                        <p>Gender: @Model.FoundPatient.Gender</p>
                        <p>Phone: @Model.FoundPatient.Phone</p>
                        <p>Address: @Model.FoundPatient.Address</p>
                    </div>
                    <div>
                        <h4>Appointments</h4>
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>Date</th>
                                    <th>Service</th>
                                    <th>Dentist</th>
                                    <th>Status</th>
                                    <th>Actions </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var appointment in Model.PatientAppointments)
                                {
                                    <tr>
                                        <td>@appointment.AppointDate</td>
                                        <td>@appointment.Service.Name</td>
                                        <td>@appointment.Dentist.Name</td>
                                        <td>@Enum.GetName(typeof(AppointmentStatus), appointment.Status)</td>
                                        <td>
                                            @if (appointment.Status != (int)AppointmentStatus.Canceled && appointment.Status != (int)AppointmentStatus.LateCanceled)
                                            {
                                                <form method="post" asp-page-handler="CheckRefund">
                                                    <input type="hidden" name="SearchTerm" value="@Model.SearchTerm" />
                                                    <input type="hidden" name="appointmentId" value="@appointment.Id" />
                                                    <button type="submit" class="btn btn-secondary">Check Refund</button>
                                                </form>
                                                <form method="post" asp-page-handler="Refund">
                                                    <input type="hidden" name="SearchTerm" value="@Model.SearchTerm" />
                                                    <input type="hidden" name="appointmentId" value="@appointment.Id" />
                                                    <button type="submit" class="btn btn-danger">Refund</button>
                                                </form>
                                            }
                                            @if (appointment.Status == (int)AppointmentStatus.Waiting)
                                            {
                                                <form method="post" asp-page-handler="CheckIn">
                                                    <input type="hidden" name="SearchTerm" value="@Model.SearchTerm" />
                                                    <input type="hidden" name="appointmentId" value="@appointment.Id" />
                                                    <button type="submit" class="btn btn-success">Check-in</button>
                                                </form>
                                            }
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    <button id="showCreateAppointmentForm" class="btn btn-primary">Create Appointment</button>
                    <div id="createAppointmentForm" style="display:none;">
                    <div class="row">
                        <form id="combinedForm" method="post" asp-page-handler="Submit">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                                <select class="form-control" asp-for="Appointment.ServiceId">
                                    @foreach (var service in Model.Services)
                                    {
                                        <option value="@service.Id">@service.Name</option>
                                    }
                                </select>
                                <span asp-validation-for="Appointment.ServiceId" class="text-danger"></span>
                            </div>


                            <div class="form-group">
                                <label asp-for="Appointment.AppointDate" class="control-label">Appointment Date</label>
                                <input type="date" asp-for="Appointment.AppointDate" class="form-control" id="Appointment_AppointDate" onchange="updateAvailableSlots();"  min="@DateTime.Now.ToString("yyyy-MM-dd")" max="@DateTime.Now.AddYears(5).ToString("yyyy-MM-dd")" />
                                <span asp-validation-for="Appointment.AppointDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Appointment.StartSlot" class="control-label">Start Slot</label>
                                <select id="appointment-slots-partial" asp-for="Appointment.StartSlot" class="form-control" onchange="updateAvailableDentists()">
                                    @* Populate slots dynamically based on appointment date and service *@
                                    @await Html.PartialAsync("_SlotPartial", new List<Slot>())
                                </select>
                                <span asp-validation-for="Appointment.StartSlot" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Appointment.DentistId" class="control-label">Dentist</label>
                                <select id="dentist-list" asp-for="Appointment.DentistId" class="form-control">
                                    @* Populate dentists dynamically based on selected slot and service *@
                                    @await Html.PartialAsync("_DentistPartial", new List<Dentist>())
                                </select>
                                <span asp-validation-for="Appointment.DentistId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">Submit Appointment</button>
                            </div>
                        </form>
                    </div>
                 </div>
                }
                else
                {
                    <div class="alert alert-info">
                        No patient found with the provided details. <a href="@Url.Page("./RegisterPatient")">Create a new patient account</a>.
                    </div>
                }
                </div>
        </div>
    </div>
</body>
<!-- Refund Modal -->
<div id="refundModal" class="modal">
    <div class="modal-content">
        <h4>Refund Amount</h4>
        <p id="refundAmount"></p>
        <input type="hidden" id="appointmentId" />
        <button id="btnRefund">Process Refund</button>
        <button class="btn-close">Close</button>
    </div>
</div>
    <script>
        function updateAvailableSlots() {
            var appointmentDate = $('#Appointment_AppointDate').val();
            var serviceDuration = @Model.Service.Duration;

            $.ajax({
                url: '@Url.Page("./Main", new { handler = "AvailableSlotsPartial" })',
                type: 'GET',
                data: { appointmentDate: appointmentDate, serviceDuration: serviceDuration },
                success: function (data) {
                    $('#appointment-slots-partial').html(data);
                    updateAvailableDentists();
                    console.log(data);
                },
                error: function (xhr, status, error) {
                    console.error('Error updating available slots:', error);
                }
            });
            updateAvailableDentists();
        }

        function updateAvailableDentists() {
            var appointmentDate = $('#Appointment_AppointDate').val();
            var serviceDuration = @Model.Service.Duration;
            var startSlot = $('#appointment-slots-partial').val();
            var serviceId = @Model.Service.Id;

            $.ajax({
                url: '@Url.Page("./Main", new { handler = "AvailableDentistsPartial" })',
                type: 'GET',
                data: {
                    appointmentDate: appointmentDate,
                    serviceDuration: serviceDuration,
                    startSlot: startSlot,
                    serviceId: serviceId
                },
                success: function (data) {
                    $('#dentist-list').html(data);
                    console.log(data);
                },
                error: function (xhr, status, error) {
                    console.error('Error retrieving available dentists:', error);
                }
            });
        }


        document.getElementById('showCreateAppointmentForm').addEventListener('click', function () {
            document.getElementById('createAppointmentForm').style.display = 'block';
        });
    
    </script>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

ClinicPresentationLayer/Pages/Staffs/RegisterPatient.cshtml
@page
@using BusinessObjects
@using BusinessObjects.Entities
@model ClinicPresentationLayer.Pages.Staffs.RegisterPatientModel
@{
}
<body class="auth">
    @if (TempData["ErrorMessage"] != null)
    {
        <div class="alert alert-danger">
            @TempData["ErrorMessage"]
        </div>
    }
    <div id="main-wrapper" class="show">
        <div class="login-tabib">
            <div>
                <div class="text-center">
                    <a class="logo" href="index.html">
                        <img class="img-fluid" src="~/images/logo.png" alt="login page">
                    </a>
                </div>
                <h4>Create new patient account</h4>
                <p>Enter patient information to create a new account</p>
                <form class="theme-form" method="post" asp-page-handler="Register">
                    <div class="form-group">
                        <label asp-for="Username" class="control-label"></label>
                        <input asp-for="Username" class="form-control" />
                        <span asp-validation-for="Username" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Password" class="control-label"></label>
                        <input asp-for="Password" class="form-control" type="password" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="DateOfBirth" class="control-label"></label>
                        <input asp-for="DateOfBirth" class="form-control" type="date" />
                        <span asp-validation-for="DateOfBirth" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Gender" class="control-label"></label>
                        <select asp-for="Gender" class="form-control">
                            <option value="M">Male</option>
                            <option value="F">Female</option>
                        </select>
                        <span asp-validation-for="Gender" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Phone" class="control-label"></label>
                        <input asp-for="Phone" class="form-control" />
                        <span asp-validation-for="Phone" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Address" class="control-label"></label>
                        <input asp-for="Address" class="form-control" />
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>
                    <button type="submit" class="btn btn-primary">Register</button>
                </form>
            </div>
        </div>
    </div>
</body>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}